source("R/ext_score_publication.R")
directory <- tempfile("ext-publication-")
dir.create(directory)
metadata <- file.path(directory, "metadata.csv")
receipt <- file.path(directory, "receipt.rds")
rank <- file.path(directory, "rank.csv")
write.csv(data.frame(season = 2026L, week = 4L, official_week = 4L), metadata, row.names = FALSE)
write.csv(data.frame(rank = 7), rank, row.names = FALSE)
stopifnot(is.null(read_ext_score_publication(receipt)))
write_ext_score_publication(metadata, receipt, rank)
stopifnot(read_ext_score_publication(receipt)$official_week == 4L)
# A later scrape alone must not advance the EXT status.
write.csv(data.frame(season = 2026L, week = 5L, official_week = 5L), metadata, row.names = FALSE)
stopifnot(read_ext_score_publication(receipt)$official_week == 4L)
write.csv(data.frame(rank = 8), rank, row.names = FALSE)
stopifnot(is.null(read_ext_score_publication(receipt)))
write_ext_score_publication(metadata, receipt, rank)
stopifnot(read_ext_score_publication(receipt)$official_week == 5L)
unlink(rank)
stopifnot(is.null(read_ext_score_publication(receipt)))
cat("EXT publication tests passed: confirmed build, scrape-only changes, mismatched ranks, and missing files.\n")
